"""Write the T2.9 golden-set review worksheet to `docs/golden-review.md`.

    python scripts/golden_worksheet.py

**Why this exists.** `tests/golden/companies.json` carries an `expected` block
per company, and six of the eight say `reviewed_by: assistant-draft` -- scored
by the same model family the audit engine runs on. That is not ground truth,
and an eval report over those rows measures agreement rather than accuracy.
This worksheet is how that gets corrected: it puts each company in front of a
human cheaply enough that disagreeing is easy.

The thing that makes that review slow is not the judgement, it is the
arithmetic: you cannot say whether a verdict is right without first working out
the margin, the runway, and the LTV:CAC from figures stored in kobo. So this
renders each company the way the audit itself sees it -- the same
`render_profile_facts` and `render_computed_figures` the prompt is built from --
next to the proposed answer and the criteria it would be graded against. The
reviewer checks a judgement instead of doing sums.

The output is committed so it can be read without a checkout of this repo, but
**no test guards it for staleness**, unlike `docs/openapi.json`. That is
deliberate: it is a worksheet, not a contract. Nothing reads it, nothing depends
on it, and it is regenerated rather than edited. The reviewed decision lands in
`companies.json`, which is what everything else reads -- so a stale worksheet
costs a re-run, not a wrong verdict.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.modules.audit.consistency import (  # noqa: E402
    check_scale,
    check_team,
    data_integrity_score,
)
from app.modules.audit.finance import compute  # noqa: E402
from app.modules.audit.pipeline import (  # noqa: E402
    financial_inputs,
    render_computed_figures,
    render_profile_facts,
)
from app.modules.audit.rubric.v1 import CORE, RUBRIC_VERSION, Scope  # noqa: E402
from app.modules.audit.synthesis import INTEGRITY_FLOOR, READY_THRESHOLD  # noqa: E402
from tests.golden import GoldenCompany, load_companies  # noqa: E402

DESTINATION = Path(__file__).resolve().parents[1] / "docs" / "golden-review.md"


def _int(fields: object, name: str) -> int | None:
    if not isinstance(fields, dict):
        return None
    entry = fields.get(name)
    if not isinstance(entry, dict):
        return None
    value = entry.get("value")
    return value if isinstance(value, int) and not isinstance(value, bool) else None


def _findings(company: GoldenCompany) -> list[object]:
    fields = company.snapshot.fields
    inputs = financial_inputs(company.snapshot)
    return [
        *check_scale(inputs, active_customers=_int(fields, "active_customers")),
        *check_team(
            team_size=_int(fields, "team_size"),
            founder_count=_int(fields, "founder_count"),
            founders_full_time=_int(fields, "founders_full_time"),
        ),
    ]


def _band(low: int | None, high: int | None) -> str:
    """A score range, or a dash where the level cannot carry one.

    `insufficient_data` is the only level that scores `None` -- `provisional` is
    a conclusion from partial evidence and still carries a mean.
    """
    if low is None and high is None:
        return "—"
    return f"{low}–{high}"


def _preamble() -> list[str]:
    return [
        "# Golden-set review worksheet",
        "",
        "> Generated by `scripts/golden_worksheet.py`. Do not edit this file — it is",
        "> regenerated. Your decisions go in `tests/golden/companies.json`.",
        "",
        "Every company in the golden set is now scored, and **two of the eight**",
        "are scored by arithmetic rather than by anyone's judgement. The other six",
        "carry `reviewed_by: assistant-draft`: Claude read the profile and scored it",
        "against the published rubric, at the owner's explicit instruction.",
        "",
        "That is worth being plain about. The audit engine runs on the same model",
        "family that wrote those expectations, so an agreement figure over those six",
        "is not a clean accuracy measurement — it is partly a measure of a model",
        "agreeing with itself. It is better than an unreviewed set, which measures",
        "nothing at all, and it is weaker than an analyst. `ReviewedBy` in",
        "`tests/golden/loader.py` keeps the distinction machine-readable so an eval",
        "report cannot quietly drop the caveat.",
        "",
        "## How to use it",
        "",
        "This is now a **challenge sheet**, not a blank one. For each company below:",
        "",
        "1. Read *what the founder submitted* and *what the platform computed*.",
        "2. Decide what the audit **should** say. Not what it does say — what a",
        "   founder deserves to be told, and what SACI is willing to put its name to.",
        "3. Compare that against the proposed answer. **Where you disagree, you are",
        "   right and the draft is wrong** — it was written without a real audit to",
        "   check it against.",
        "4. Edit the `expected` block shown at the end of each section, in",
        '   `tests/golden/companies.json`, and set `"reviewed_by": "human"` on any',
        "   company you have personally decided.",
        "",
        "The companies marked `deterministic` need no review at all: their verdicts",
        "come from the integrity floor and the coverage ratio, and no model output",
        "reaches them. Spend the time on the six that say `assistant-draft`.",
        "",
        "Score bands, not exact numbers. A model-derived dimension score is not",
        "reproducible to the unit, so an exact expectation would fail on noise and",
        "teach everyone to ignore the harness. Pick the range you would accept.",
        "",
        "## The four things a verdict can be",
        "",
        "| Level | Means | Carries a score? |",
        "|---|---|---|",
        "| `ready` | Meets the bar on well-evidenced dimensions. | yes |",
        "| `not_yet` | Enough evidence to judge, and it misses the bar. | yes |",
        "| `provisional` | A conclusion, but the evidence is thin. "
        "Never show it as a plain result. | yes |",
        "| `insufficient_data` | No conclusion. An absence, not a failure — "
        "never render it as 'not fundable'. | no |",
        "",
        "Two thresholds decide these mechanically, and both are worth having in mind",
        "while you score:",
        "",
        f"- **`READY_THRESHOLD` = {READY_THRESHOLD}.** Mean score at or above which a",
        "  verdict reads `ready`. Deliberately untuned — it is a round number chosen",
        "  before any golden set existed. **This review is what tunes it.**",
        f"- **`INTEGRITY_FLOOR` = {INTEGRITY_FLOOR}.** Below this "
        "`data_integrity_score`,",
        "  no verdict is offered at all and the rubric is never called.",
        "",
    ]


def _rubric_reference() -> list[str]:
    lines = [
        "## What the audit grades",
        "",
        f"Rubric `{RUBRIC_VERSION}`. The same dimensions apply to every company, so",
        "they are listed once here rather than repeated below. Each verdict is the",
        "mean of the dimensions in its scope that carried real evidence.",
        "",
    ]
    for spec in CORE:
        scope = {
            Scope.BOTH: "fundability + saleability",
            Scope.FUNDABILITY: "fundability only",
            Scope.SALEABILITY: "saleability only",
        }[spec.scope]
        lines += [
            f"### {spec.title}",
            "",
            f"*{spec.question}*",
            "",
            f"Scope: {scope} · weight {spec.weight}",
            "",
        ]
        lines += [f"- {criterion}" for criterion in spec.criteria]
        lines.append("")
    return lines


def _summary(companies: tuple[GoldenCompany, ...]) -> list[str]:
    lines = [
        "## At a glance",
        "",
        "Read this first: the spread matters as much as any single company. If every",
        "proposed verdict is `not_yet`, the set is not exercising the rubric.",
        "",
        "| # | Company | Proposed fundability | Proposed saleability "
        "| Integrity | Scored by |",
        "|---|---|---|---|---|---|",
    ]
    for index, company in enumerate(companies, start=1):
        integrity = data_integrity_score(_findings(company))  # type: ignore[arg-type]
        source = company.reviewed_by.value
        lines.append(
            f"| {index} | `{company.id}` "
            f"| {company.fundability.level.value} "
            f"({_band(company.fundability.score_min, company.fundability.score_max)}) "
            f"| {company.saleability.level.value} "
            f"({_band(company.saleability.score_min, company.saleability.score_max)}) "
            f"| **{integrity}** "
            f"| {source if source != 'assistant-draft' else f'**{source}**'} |"
        )
    lines.append("")
    return lines


def _company_section(index: int, company: GoldenCompany) -> list[str]:
    findings = _findings(company)
    integrity = data_integrity_score(findings)  # type: ignore[arg-type]
    summary = compute(financial_inputs(company.snapshot))

    lines = [
        f"## {index}. `{company.id}`",
        "",
        f"**Why this company is in the set.** {company.why_this_case}",
        "",
        "### What the founder submitted",
        "",
        "```",
        render_profile_facts(company.snapshot).strip(),
        "```",
        "",
        "### What the platform computed",
        "",
        "Derived in code, never by the model (D9). These are the figures the audit",
        "reasons from, so a verdict that disagrees with them needs a reason.",
        "",
        "```",
        render_computed_figures(summary).strip(),
        "```",
        "",
        "### Consistency",
        "",
        f"`data_integrity_score` = **{integrity}** "
        f"(floor is {INTEGRITY_FLOOR}; below it, no verdict is offered)",
        "",
    ]

    if findings:
        lines.append("Findings that fired:")
        lines.append("")
        for finding in findings:
            code = finding.code.value  # type: ignore[attr-defined]
            severity = finding.severity.value  # type: ignore[attr-defined]
            detail = finding.detail  # type: ignore[attr-defined]
            lines.append(f"- **{code}** ({severity}) — {detail}")
        lines.append("")
    else:
        lines += ["No findings: the submitted figures agree with each other.", ""]

    lines += [
        "### Proposed answer — this is what needs checking",
        "",
        "| | Level | Score band |",
        "|---|---|---|",
        f"| Fundability | `{company.fundability.level.value}` "
        f"| {_band(company.fundability.score_min, company.fundability.score_max)} |",
        f"| Saleability | `{company.saleability.level.value}` "
        f"| {_band(company.saleability.score_min, company.saleability.score_max)} |",
        f"| Data integrity | — "
        f"| {company.data_integrity_min}–{company.data_integrity_max} |",
        "",
    ]

    if company.verdict_is_model_dependent:
        lines += [
            "> This verdict depends on dimension scores from `claude-opus-5`, so it",
            "> cannot be checked without a billed run. Your judgement here is the",
            "> only thing that will make that run meaningful.",
            "",
        ]
    else:
        lines += [
            "> This verdict is decided by arithmetic alone — the integrity floor or",
            "> the coverage ratio — so the deterministic suite already asserts it and",
            "> no model call is involved.",
            "",
        ]

    if company.must_flag:
        codes = ", ".join(f"`{code.value}`" for code in company.must_flag)
        lines += [f"Expected to flag: {codes}", ""]

    lines += [
        "### To record your decision",
        "",
        f"In `tests/golden/companies.json`, on `{company.id}`:",
        "",
        "```json",
        '"expected": {',
        '  "reviewed": true,',
        '  "reviewed_by": "human",',
        f'  "fundability": {{ "level": "{company.fundability.level.value}", '
        f'"score_min": {company.fundability.score_min}, '
        f'"score_max": {company.fundability.score_max} }},',
        f'  "saleability": {{ "level": "{company.saleability.level.value}", '
        f'"score_min": {company.saleability.score_min}, '
        f'"score_max": {company.saleability.score_max} }},',
        f'  "data_integrity_min": {company.data_integrity_min},',
        f'  "data_integrity_max": {company.data_integrity_max},',
        '  "must_flag": ['
        + ", ".join(f'"{code.value}"' for code in company.must_flag)
        + "]",
        "}",
        "```",
        "",
        "---",
        "",
    ]
    return lines


def main() -> int:
    companies = load_companies()

    lines = _preamble()
    lines += _summary(companies)
    lines += _rubric_reference()
    lines += ["---", ""]
    for index, company in enumerate(companies, start=1):
        lines += _company_section(index, company)

    counts: dict[str, int] = {}
    for company in companies:
        counts[company.reviewed_by.value] = counts.get(company.reviewed_by.value, 0) + 1
    breakdown = ", ".join(f"{count} {name}" for name, count in sorted(counts.items()))

    lines += [
        "## When you are done",
        "",
        f"{len(companies)} companies: {breakdown}.",
        "",
        "The accuracy half of T2.9 can be built and run against this set now. What",
        "it cannot do is call the result *accuracy* without qualification, because",
        "of the `assistant-draft` rows above. Every company you re-decide and mark",
        "`human` moves one row out of that caveat and makes the figure mean more.",
        "",
        "Two structural findings came out of the scoring pass and are worth reading",
        "before you disagree with any band — both are in `TASKS.md` under T2.9:",
        "",
        "- **`ready` and `not_yet` need every in-scope dimension evidenced.** One",
        "  hedged dimension collapses the verdict to `provisional`, so the four",
        "  non-provisional expectations here are the fragile ones.",
        "- **Nothing in the Startup Profile supplies `market_opportunity` or",
        "  `scalability`.** Their substance has to be hand-written into the",
        "  description and business model, which is why several companies here read",
        "  more fully than a real founder's submission would. That gap is a field-set",
        "  question, not a fixture question.",
        "",
    ]

    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text("\n".join(lines), encoding="utf-8")

    print(
        f"wrote {DESTINATION}\n"
        f"  {len(companies)} companies ({breakdown}), "
        f"{len(CORE)} rubric dimensions"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
