"""Turning an audit's action plan into readiness tasks (T3.1).

Layer: **service** (ARCHITECTURE.md section 3). Pure: no I/O, no database, no
model call. Everything here is a function of one `AuditReport`.

**A task is not a second opinion about the report.** The audit already decided
what is wrong and wrote each gap as an action (`synthesis.ActionItem`, derived
from the rubric's `unmet_criteria`). This module only decides two things the
report does not say on its own: whether closing a gap is *necessary* to reach
`ready`, and how to recognise the same gap again on the next audit. Asking a
model either question would make the founder's obligations non-deterministic --
the same report could generate a required task one day and a recommended one the
next, which is the failure T2.9 exists to prevent, moved downstream.

**Required is computed from `READY_THRESHOLD`, not chosen.** PRD section 4.2
says blocking gaps become required tasks and the rest become recommended, so
"blocking" has to mean something arithmetic. It means exactly what
`synthesis._verdict_for` means by it -- see `classify`. The constant is imported
rather than restated: a second copy would drift the first time the threshold
moved, and the drift would silently change what founders are obliged to do.
"""

import hashlib
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from enum import StrEnum
from typing import Final

from app.modules.audit.rubric.v1 import Dimension
from app.modules.audit.synthesis import READY_THRESHOLD, ActionItem, AuditReport

__all__ = [
    "GeneratedTask",
    "Requirement",
    "TaskStatus",
    "action_fingerprint",
    "classify",
    "plan_for_report",
]


class Requirement(StrEnum):
    """Whether a founder must close this gap to become investor-visible.

    The distinction is the whole point of the readiness loop: the gate in T3.6
    is "audit cleared **and** all required tasks passed", so `RECOMMENDED` is
    genuinely optional and `REQUIRED` genuinely blocks. Marking everything
    required would make the gate unreachable; marking nothing required would
    make it meaningless.
    """

    REQUIRED = "required"
    """Closing this is necessary for a `ready` verdict."""

    RECOMMENDED = "recommended"
    """Worth doing. The dimension already clears the bar without it."""


class TaskStatus(StrEnum):
    """Where a task sits in the evidence loop (PRD section 4.2).

    **The full lifecycle is declared here although only two states are
    reachable in T3.1.** `SUBMITTED`, `PASSED`, `FAILED` and `NEEDS_MORE` are
    written by evidence assessment in T3.5. Declaring them now is deliberate on
    two grounds: `CLAUDE.md` section 6 requires every enum the mobile client
    depends on to be documented, and the client builds its task UI once rather
    than twice; and the column is a non-native enum backed by a check
    constraint, so adding values later is a migration on live rows. The cost of
    declaring early is a docstring; the cost of declaring late is a schema
    change plus a client release.

    `CLIENTS.md` says which states are reachable today, so nobody builds against
    a promise that has not landed.
    """

    OPEN = "open"
    """Generated by an audit and not yet acted on."""

    SUBMITTED = "submitted"
    """Evidence uploaded, awaiting assessment. Unreachable until T3.5."""

    PASSED = "passed"
    """Evidence assessed as sufficient. Unreachable until T3.5."""

    FAILED = "failed"
    """Evidence assessed as insufficient, with reasons. Unreachable until T3.5."""

    NEEDS_MORE = "needs_more"
    """Partial evidence; more is required. Unreachable until T3.5."""

    OBSOLETE = "obsolete"
    """A later audit no longer raises this gap, and no work was done on it."""


UNTOUCHED_STATUSES: Final[frozenset[TaskStatus]] = frozenset({TaskStatus.OPEN})
"""The only statuses a regenerating audit may overwrite with `OBSOLETE`.

**A record of work a founder actually did is never erased by a re-audit.** Once
evidence has been uploaded the row carries history -- what was submitted, how it
was graded, why it failed -- and a later audit that stops raising the gap does
not make that history untrue. Only a task nobody has touched can be retired
silently.

The narrow definition is the point. `FAILED` looks retirable and is not: a
failed task has evidence attached and a founder who is owed the reason.
"""


@dataclass(frozen=True, slots=True)
class GeneratedTask:
    """One task the audit is asking for, before it meets the database.

    Frozen and free of identifiers on purpose: this is what the report *says*,
    and reconciling it against what is already stored is the repository's job
    (`service.generate_for_report`). Keeping the two apart is what lets the
    classification be tested without a database.
    """

    dimension: Dimension
    action: str
    requirement: Requirement
    dimension_score: int | None
    is_priority: bool
    fingerprint: str


_WHITESPACE: Final = re.compile(r"\s+")


def _normalise(action: str) -> str:
    """Collapse the differences that are not differences.

    Whitespace and case only. The model writes each action afresh on every run,
    so an identical gap can come back as `"Publish a  pricing page"` where it
    was `"Publish a pricing page"`; folding those keeps one task instead of two.

    **This does not survive rewording**, and nothing here pretends otherwise: an
    action rephrased as "Add pricing to the website" fingerprints differently
    and produces a second task alongside the first. The honest fix is semantic
    matching, which needs embeddings -- still blocked on the provider decision
    in TASKS.md -- so the shape a founder sees today is occasional near
    duplicates rather than lost tasks. Duplicates are visible and dismissible;
    silently merging two genuinely different actions is not.
    """
    return _WHITESPACE.sub(" ", action).strip().casefold()


def action_fingerprint(dimension: Dimension, action: str) -> str:
    """A stable id for "this gap, on this dimension".

    The key a re-audit reconciles against, so it has to be derived from the
    content rather than assigned: an id minted per run would make every audit
    generate a fresh set of tasks and lose the founder's progress on all of
    them.

    Includes the dimension, so the same sentence raised under two dimensions is
    two tasks. That is correct -- "state your assumptions" means different work
    under `financial_health` than under `market_opportunity`, and the founder
    is owed both.

    The unit separator cannot appear in either input, so no dimension/action
    pair can collide with another by concatenation.
    """
    payload = f"{dimension.value}\x1f{_normalise(action)}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def classify(dimension_score: int | None) -> Requirement:
    """Whether this gap blocks a `ready` verdict.

    Two ways a dimension keeps a verdict away from `ready`, and both are read
    straight off `synthesis._verdict_for`:

    * **It could not be scored.** `dimension_score is None` means the rubric
      returned `insufficient_data`, which puts the dimension in
      `Verdict.unevidenced_dimensions` and trips the `thin` rule -- and `thin`
      forces `provisional` regardless of how high the score is. No amount of
      strength elsewhere clears it, so closing it is required.
    * **It scored below the bar.** Anything under `READY_THRESHOLD` pulls the
      weighted mean down; a dimension at or above it does not.

    Anything else is `RECOMMENDED`: the dimension already clears the bar, so the
    action would improve a score that is not what is holding the founder back.

    **A dimension at exactly `READY_THRESHOLD` is not blocking.** The verdict
    rule is `mean >= READY_THRESHOLD`, so the boundary belongs on the passing
    side in both places. Off-by-one here would oblige a founder to work on a
    dimension the verdict considers satisfactory.

    This is deliberately about the *dimension*, not the weighted mean. A
    founder cannot act on an average; they act on the thing that scored badly,
    and a dimension under the bar is under it whichever verdict it feeds.
    """
    if dimension_score is None:
        return Requirement.REQUIRED
    if dimension_score < READY_THRESHOLD:
        return Requirement.REQUIRED
    return Requirement.RECOMMENDED


def plan_for_report(report: AuditReport) -> tuple[GeneratedTask, ...]:
    """Every task one audit asks for, in the report's own order.

    Order is preserved rather than re-sorted: `synthesis._action_plan` already
    ordered the plan worst-first so a founder with limited time works on what is
    holding them back most, and re-deriving that ordering here would be a second
    copy of the same rule.

    **Deduplicated by fingerprint within the run.** A single report can raise
    the same normalised action twice -- two dimensions is a genuine pair and
    keeps both, but the same dimension repeating itself is one gap stated twice
    and would otherwise violate the uniqueness the storage layer relies on. The
    first occurrence wins, which under the plan's worst-first ordering is the
    one carrying the more urgent context.
    """
    return _from_items(report.action_plan)


def _from_items(items: Sequence[ActionItem]) -> tuple[GeneratedTask, ...]:
    seen: set[str] = set()
    tasks: list[GeneratedTask] = []
    for item in items:
        fingerprint = action_fingerprint(item.dimension, item.action)
        if fingerprint in seen:
            continue
        seen.add(fingerprint)
        tasks.append(
            GeneratedTask(
                dimension=item.dimension,
                action=item.action,
                requirement=classify(item.dimension_score),
                dimension_score=item.dimension_score,
                is_priority=item.is_priority,
                fingerprint=fingerprint,
            )
        )
    return tuple(tasks)


def required_count(tasks: Iterable[GeneratedTask]) -> int:
    """How many of these block the gate. Used for logging and the response."""
    return sum(1 for task in tasks if task.requirement is Requirement.REQUIRED)
