"""Readiness tasks generated from an audit's action plan (T3.1).

`uq_readiness_tasks_action` is the load-bearing part. Every audit rewrites its
whole action plan, so without a content-derived key a re-audit would insert a
second copy of every task and strand the founder's progress on the first set.
Keying on startup + action fingerprint makes regeneration a reconcile rather
than a rewrite -- see `readiness.models.ReadinessTask`.

`audit_run_id` is nullable with `ON DELETE SET NULL` on purpose: deleting a run
must not delete the founder's task history along with it.

Revision ID: 0012_readiness_tasks
Revises: 0011_brokerage
Create Date: 2026-08-05 11:15:19.792813+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0012_readiness_tasks'
down_revision: str | None = '0011_brokerage'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('audit_run_id', sa.Uuid(), nullable=True),
    sa.Column('dimension', sa.Enum('financial_health', 'unit_economics', 'traction', 'market_opportunity', 'team', 'legal_and_ip', 'data_integrity', 'scalability', 'owner_independence', 'transferability', 'revenue_durability', name='rubric_dimension', native_enum=False, length=32), nullable=False),
    sa.Column('action', sa.String(length=1000), nullable=False),
    sa.Column('action_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('requirement', sa.Enum('required', 'recommended', name='task_requirement', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('open', 'submitted', 'passed', 'failed', 'needs_more', 'obsolete', name='task_status', native_enum=False, length=16), server_default='open', nullable=False),
    sa.Column('dimension_score', sa.Integer(), nullable=True),
    sa.Column('is_priority', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], name=op.f('fk_readiness_tasks_audit_run_id_audit_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_readiness_tasks_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startup_profiles.id'], name=op.f('fk_readiness_tasks_startup_id_startup_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readiness_tasks')),
    sa.UniqueConstraint('startup_id', 'action_fingerprint', name='uq_readiness_tasks_action')
    )
    op.create_index(op.f('ix_readiness_tasks_action_fingerprint'), 'readiness_tasks', ['action_fingerprint'], unique=False)
    op.create_index(op.f('ix_readiness_tasks_audit_run_id'), 'readiness_tasks', ['audit_run_id'], unique=False)
    op.create_index(op.f('ix_readiness_tasks_dimension'), 'readiness_tasks', ['dimension'], unique=False)
    op.create_index(op.f('ix_readiness_tasks_owner_id'), 'readiness_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_readiness_tasks_requirement'), 'readiness_tasks', ['requirement'], unique=False)
    op.create_index(op.f('ix_readiness_tasks_startup_id'), 'readiness_tasks', ['startup_id'], unique=False)
    op.create_index(op.f('ix_readiness_tasks_status'), 'readiness_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readiness_tasks_status'), table_name='readiness_tasks')
    op.drop_index(op.f('ix_readiness_tasks_startup_id'), table_name='readiness_tasks')
    op.drop_index(op.f('ix_readiness_tasks_requirement'), table_name='readiness_tasks')
    op.drop_index(op.f('ix_readiness_tasks_owner_id'), table_name='readiness_tasks')
    op.drop_index(op.f('ix_readiness_tasks_dimension'), table_name='readiness_tasks')
    op.drop_index(op.f('ix_readiness_tasks_audit_run_id'), table_name='readiness_tasks')
    op.drop_index(op.f('ix_readiness_tasks_action_fingerprint'), table_name='readiness_tasks')
    op.drop_table('readiness_tasks')
    # ### end Alembic commands ###
