"""Brokerage: interests, report reveals, and investor visibility (T4.3, T4.5, T4.6).

Revision ID: 0011_brokerage
Revises: 0010_audit_runs
Create Date: 2026-08-03 15:54:44.385681+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0011_brokerage'
down_revision: str | None = '0010_audit_runs'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', 'withdrawn', name='interest_status', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_interests_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], name=op.f('fk_interests_investor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startup_profiles.id'], name=op.f('fk_interests_startup_id_startup_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interests')),
    sa.UniqueConstraint('investor_id', 'startup_id', name='uq_interest_pair')
    )
    op.create_index(op.f('ix_interests_investor_id'), 'interests', ['investor_id'], unique=False)
    op.create_index(op.f('ix_interests_startup_id'), 'interests', ['startup_id'], unique=False)
    op.create_index(op.f('ix_interests_status'), 'interests', ['status'], unique=False)
    op.create_table('report_reveals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.Column('audit_run_id', sa.Uuid(), nullable=False),
    sa.Column('revealed_by_id', sa.Uuid(), nullable=True),
    sa.Column('revealed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], name=op.f('fk_report_reveals_audit_run_id_audit_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_report_reveals_interest_id_interests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revealed_by_id'], ['users.id'], name=op.f('fk_report_reveals_revealed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_reveals')),
    sa.UniqueConstraint('interest_id', 'audit_run_id', name='uq_reveal_pair')
    )
    op.create_index(op.f('ix_report_reveals_audit_run_id'), 'report_reveals', ['audit_run_id'], unique=False)
    op.create_index(op.f('ix_report_reveals_interest_id'), 'report_reveals', ['interest_id'], unique=False)
    op.add_column('startup_profiles', sa.Column('investor_visible', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('startup_profiles', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_startup_profiles_investor_visible'), 'startup_profiles', ['investor_visible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startup_profiles_investor_visible'), table_name='startup_profiles')
    op.drop_column('startup_profiles', 'published_at')
    op.drop_column('startup_profiles', 'investor_visible')
    op.drop_index(op.f('ix_report_reveals_interest_id'), table_name='report_reveals')
    op.drop_index(op.f('ix_report_reveals_audit_run_id'), table_name='report_reveals')
    op.drop_table('report_reveals')
    op.drop_index(op.f('ix_interests_status'), table_name='interests')
    op.drop_index(op.f('ix_interests_startup_id'), table_name='interests')
    op.drop_index(op.f('ix_interests_investor_id'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
