"""Evidence uploads and the per-task assessment attempt cap (T3.5).

`readiness_tasks.assessment_attempts` is the load-bearing addition. Grading is a
model call, a model does not answer identically twice, and the outcome decides
whether a founder passes into investor visibility -- so without a cap a
determined founder eventually passes anything, at a billed AUDIT-tier call each
time. Added with `server_default='0'` so existing rows land at zero rather than
NULL, which would read as "unlimited" to `attempts_remaining`.

`evidence.storage_key` is unique for the same reason `documents.storage_key` is:
two rows pointing at one object means deleting one row orphans or destroys the
other's bytes.

Revision ID: 0013_evidence
Revises: 0012_readiness_tasks
Create Date: 2026-08-05 12:12:26.990062+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0013_evidence'
down_revision: str | None = '0012_readiness_tasks'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', 'rejected', name='evidence_status', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('outcome', sa.Enum('pass', 'fail', 'needs_more', name='assessment_outcome', native_enum=False, length=16), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessment_prompt_ref', sa.String(length=60), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_evidence_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startup_profiles.id'], name=op.f('fk_evidence_startup_id_startup_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['readiness_tasks.id'], name=op.f('fk_evidence_task_id_readiness_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_evidence_storage_key'))
    )
    op.create_index(op.f('ix_evidence_outcome'), 'evidence', ['outcome'], unique=False)
    op.create_index(op.f('ix_evidence_owner_id'), 'evidence', ['owner_id'], unique=False)
    op.create_index(op.f('ix_evidence_startup_id'), 'evidence', ['startup_id'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_task_id'), 'evidence', ['task_id'], unique=False)
    op.add_column('readiness_tasks', sa.Column('assessment_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readiness_tasks', 'assessment_attempts')
    op.drop_index(op.f('ix_evidence_task_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_startup_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_owner_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_outcome'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
